// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Clinica.AcceptanceTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Gestión de Citas Médicas")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class GestionDeCitasMedicasFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("es"), "Features", "Gestión de Citas Médicas", "    Como usuario administrativo del sistema SIGEC\r\n    Quiero programar, reprogra" +
                "mar y cancelar citas obstétricas\r\n    Para mantener la agenda del Centro Materno" +
                " Perinatal permanentemente actualizada", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "Citas.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 7
#line hidden
#line 8
    await testRunner.GivenAsync("que el usuario ha iniciado sesión como administrador", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 9
    await testRunner.AndAsync("navega a la página de citas \"/panel/citas\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Citas.feature.ndjson", 6);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Programar una nueva cita exitosamente")]
        public async global::System.Threading.Tasks.Task ProgramarUnaNuevaCitaExitosamente()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Programar una nueva cita exitosamente", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 11
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
#line 12
    await testRunner.WhenAsync("hace clic en el botón \"Nueva cita\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 13
    await testRunner.AndAsync("selecciona el paciente \"Maria Lopez Quispe\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 14
    await testRunner.AndAsync("selecciona el especialista \"Carlos Ramirez\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 15
    await testRunner.AndAsync("selecciona el servicio clínico \"Consulta obstétrica\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 16
    await testRunner.AndAsync("configura una fecha y hora disponibles sin conflictos", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 17
    await testRunner.AndAsync("escribe en el motivo clínico \"Control prenatal de rutina.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 18
    await testRunner.AndAsync("hace clic en el botón \"Programar cita\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 19
    await testRunner.ThenAsync("el sistema muestra una alerta de éxito con el mensaje \"Cita programada\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
#line 20
    await testRunner.AndAsync("la grilla de citas muestra una cita para el paciente \"Maria Lopez Quispe\" con est" +
                        "ado \"Pendiente\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Validación de campos obligatorios al crear cita")]
        public async global::System.Threading.Tasks.Task ValidacionDeCamposObligatoriosAlCrearCita()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Validación de campos obligatorios al crear cita", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 22
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
#line 23
    await testRunner.WhenAsync("hace clic en el botón \"Nueva cita\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 24
    await testRunner.AndAsync("hace clic directamente en el botón \"Programar cita\" sin llenar los campos", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 25
    await testRunner.ThenAsync("el formulario muestra errores de validación para los campos requeridos", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Reprogramar una cita existente")]
        public async global::System.Threading.Tasks.Task ReprogramarUnaCitaExistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Reprogramar una cita existente", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 27
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
#line 28
    await testRunner.GivenAsync("que se ha creado una cita de prueba para el paciente \"Maria Lopez Quispe\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 29
    await testRunner.AndAsync("se ha obtenido el código de la cita generada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 30
    await testRunner.WhenAsync("hace clic en el botón \"Reprogramar Bloque\" de la cita capturada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 31
    await testRunner.AndAsync("configura la nueva fecha \"16/06/2030\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 32
    await testRunner.AndAsync("configura el nuevo horario de inicio \"09:00\" y fin \"09:30\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 33
    await testRunner.AndAsync("escribe el motivo de reprogramación \"Ajuste de agenda operativa por emergencia en" +
                        " sala de partos.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 34
    await testRunner.AndAsync("hace clic en el botón \"Reprogramar\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 35
    await testRunner.ThenAsync("el sistema muestra una alerta de éxito con el mensaje \"Cita reprogramada\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
#line 36
    await testRunner.AndAsync("la grilla de citas muestra la cita capturada con estado \"Reprogramada\" y el nuevo" +
                        " horario \"09:00 - 09:30\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Cancelar una cita vigente")]
        public async global::System.Threading.Tasks.Task CancelarUnaCitaVigente()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cancelar una cita vigente", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 38
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
#line 39
    await testRunner.GivenAsync("que se ha creado una cita de prueba para el paciente \"Maria Lopez Quispe\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 40
    await testRunner.AndAsync("se ha obtenido el código de la cita generada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 41
    await testRunner.WhenAsync("hace clic en el botón \"Anular Ticket\" de la cita capturada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 42
    await testRunner.AndAsync("escribe el motivo de cancelación \"Paciente solicita desistir de la consulta por m" +
                        "otivos laborales de fuerza mayor.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 43
    await testRunner.AndAsync("hace clic en el botón \"Confirmar cancelación\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 44
    await testRunner.ThenAsync("el sistema muestra una alerta de éxito con el mensaje \"Cita cancelada\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
#line 45
    await testRunner.AndAsync("la grilla de citas muestra la cita capturada con estado \"Cancelada\" y sin accione" +
                        "s de reprogramación o anulación", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
